### ISSUE TITLE
Getting "RNDC handshake incomplete"

### ISSUE THREAD

**Issue by ventz** [isc-projects/bind9-rndc-node#1]
Hi,

Getting a `RNDC handshake incomplete`, with error:

```
Error: RNDC handshake incomplete
    at Socket.RNDC_Protocol.socket.on (/root/test/node_modules/bind9-rndc/lib/protocol.js:86:24)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

```
# node -v
v8.12.0
```

```
# Bind version:
bind-9.9.4
```

First tired using sha512 key, and later using sha256 just to eliminate larger key size - same error.
Originating from system running bind itself. RNDC from the CLI works with the same key.

Please let me know if I can provide anything else for debugging.

Thanks.

**Comment by ventz** [comment]
It looks like the CLI locally uses sockets and not tcp/953, and at least on Amazon Linux (v2) the controls are no longer a default:

```
controls {
        inet 127.0.0.1 port 953
        allow { 127.0.0.1; } keys { "rndc-key"; };
};
```

After adding it - it works. This is good to know :)
